name: Build and Push to Harbor (Feature)

on:
  push:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest
    environment: feature # <-- Access environment secrets
    env:
      REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
      PROJECT: ${{ secrets.HARBOR_PROJECT }}
      IMAGE: springboot-app

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Step 3: Build project with Gradle
      - name: Build with Gradle
        run: ./gradlew build -x test || gradle build -x test

      # Step 4: Log in to Harbor using environment secrets
      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_ROBOT_USERNAME }}
          password: ${{ secrets.HARBOR_ROBOT_PASSWORD }}

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$PROJECT/$IMAGE:latest .

      # Step 6: Push Docker image
      - name: Push Docker image
        run: docker push $REGISTRY/$PROJECT/$IMAGE:latest
