name: Build and Push to Harbor

on:
  push:
    branches:
      - feature

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.HARBOR_REGISTRY }}
      PROJECT: ${{ secrets.HARBOR_PROJECT }}
      IMAGE: springboot-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew build -x test || gradle build -x test

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_ROBOT_USERNAME }}
          password: ${{ secrets.HARBOR_ROBOT_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t $REGISTRY/$PROJECT/$IMAGE:latest \
            .
      - name: Push Docker image
        run: docker push $REGISTRY/$PROJECT/$IMAGE:latest
