name: ci-build

on:
  push:
    branches:
      - main
      - "feature/**"
      - "fix/**"
  workflow_dispatch:

permissions:
  contents: read

env:
  JAVA_VERSION: "17"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - - uses: gradle/actions/setup-gradle@v3
        - run: ./gradlew build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs/*.jar
          if-no-files-found: error
