name: Build and Push Docker Image

on:
  push:
    branches:
      - master   # Change branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Build with Gradle
      - name: Build with Gradle
        run: ./gradlew build -x test || gradle build -x test

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # Build Docker Image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:latest .

      # Push Docker Image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/springboot-app:latest
