name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install Gradle Wrapper (if missing)
      - name: Set up Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      # 3. Generate gradlew if it doesn't exist
      - name: Generate Gradle Wrapper
        run: |
          gradle wrapper --gradle-version 8.7
          chmod +x gradlew

      # 4. Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 5. Build with Gradle (using wrapper)
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 6. Login to Harbor
      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      # 7. Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT_NAME }}/springboot-app:latest .

      # 8. Push to Harbor
      - name: Push Docker image to Harbor
        run: docker push ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT_NAME }}/springboot-app:latest
