name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Fix Gradle permissions (critical fix)
      - name: Make gradlew executable
        run: chmod +x gradlew

      # 3. Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 4. Build with Gradle (skipping tests)
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 5. Login to Harbor registry
      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      # 6. Build Docker image with Harbor tag
      - name: Build Docker image
        run: docker build -t ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT_NAME }}/springboot-app:latest .

      # 7. Push to Harbor
      - name: Push Docker image to Harbor
        run: docker push ${{ secrets.HARBOR_REGISTRY }}/${{ secrets.HARBOR_PROJECT_NAME }}/springboot-app:latest
