name: Build and Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew build -x test || gradle build -x test

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.cloudops.terv.pro        # change to your Harbor host (add :port if needed)
          username: ${{ secrets.HARBOR_USERNAME }}  # e.g., robot$project+ci
          password: ${{ secrets.HARBOR_PASSWORD }}  # robot token/password

      - name: Build Docker image
        run: docker build -t  harbor.cloudops.terv.pro/preview/springboot-app:latest .

      - name: Push Docker image
        run: docker push harbor.cloudops.terv.pro/preview/springboot-app:latest 
